version: '2'
services:
    jhipsterpgrnd-app:
        image: jhipsterpgrnd
        external_links:
            - jhipsterpgrnd-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/jhipsterpgrnd
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterpgrnd-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterpgrnd-postgresql
